<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <WindowsSdkPackageVersion>10.0.26100.56</WindowsSdkPackageVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>FluidBackground.WinUI</RootNamespace>
    <Description>WinUI 3适配层</Description>
    <UseWinUI>true</UseWinUI>
    <RuntimeIdentifiers>win-x64;win-x86;win-arm64</RuntimeIdentifiers>
    <Platforms>x64;x86;ARM64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
    <PackageReference Include="SkiaSharp.Views.WinUI" Version="3.119.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FluidBackground.Core\FluidBackground.Core.csproj" />
  </ItemGroup>
</Project>
